In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names = names)

In [2]:
data.describe()

,preg,plas,pres,skin,test,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [3]:
data.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [4]:
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
scatter_matrix(data)
plt.show()

In [5]:
from sklearn.preprocessing import StandardScaler
datan = data.values
X = datan[:,0:8]
Y = datan[:,8]

In [6]:
import numpy as np
scalar = StandardScaler().fit(X)
datar = scalar.transform(X)
np.set_printoptions(precision = 3)
print(datar[:10,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]
 [ 0.343 -0.153  0.253 -1.288 -0.693 -0.811 -0.818 -0.276]
 [-0.251 -1.342 -0.988  0.719  0.071 -0.126 -0.676 -0.616]
 [ 1.828 -0.184 -3.573 -1.288 -0.693  0.42  -1.02  -0.361]
 [-0.548  2.382  0.046  1.535  4.022 -0.189 -0.948  1.681]
 [ 1.234  0.128  1.39  -1.288 -0.693 -4.06  -0.724  1.766]]

In [7]:
data.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

kFold = KFold(n_splits = 10, random_state = 7)
model = LogisticRegression(solver = 'liblinear')
results = cross_val_score(model, X, Y, cv = kFold)
print("Accuracy: {0} ({1})" .format(results.mean()*100.0, results.std()*100.0))

scoring = 'neg_log_loss'
results = cross_val_score(model, X, Y, cv = kFold, scoring = scoring)
print("Accuracy: {0} ({1})" .format(results.mean()*100.0, results.std()*100.0))

Accuracy: 76.95146958304852 (4.841051924567195)
Accuracy: -49.25542125228744 (4.700518583644249)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
#from sklearn.tree.export import export_text

scoring = 'accuracy'
kfold = KFold(n_splits=10, random_state=7)
#KNN
model = KNeighborsClassifier(n_neighbors = 3)
cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("Accuracy: {0} ({1})" .format(cv_results.mean(), cv_results.std()))

model = svm.SVC(gamma = 'scale')
cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("Accuracy: {0} ({1})" .format(cv_results.mean()*100.0, cv_results.std()*100.0))

model = tree.DecisionTreeClassifier()
cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("Accuracy: {0} ({1})" .format(cv_results.mean()*100.0, cv_results.std()*100.0))
# = export_text(decision_tree, feature_names=data['feature_names'])

model = RandomForestClassifier(n_estimators=100, max_depth=3)
cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("Accuracy: {0} ({1})" .format(cv_results.mean()*100.0, cv_results.std()*100.0))

model = SGDClassifier(max_iter=1000, tol=1e-3)
cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("Accuracy: {0} ({1})" .format(cv_results.mean()*100.0, cv_results.std()*100.0))

Accuracy: 0.7056049213943951 (0.060560685007924546)
Accuracy: 76.04237867395763 (5.293077027238117)
Accuracy: 68.350991114149 (5.800444761635905)
Accuracy: 75.7792207792208 (5.407602585251903)
Accuracy: 56.24914559125085 (5.875152387113114)

In [10]:
from sklearn.model_selection import GridSearchCV
import numpy as nd

In [11]:
c_val = nd.array([10,1,0.1,0.01,0.001,0.0001])
parameters = {'C':c_val}
model = LogisticRegression(solver = 'liblinear')
#model = GridSearchCV(lr, parameters, cv=5)
grid = GridSearchCV(estimator=model, param_grid=parameters, cv=3)
grid.fit(X, Y)
print(grid.best_score_)
print(grid.best_estimator_.C)

0.76953125
1.0

In [13]:
from sklearn.linear_model import Ridge
alphas = nd.array([1,0.1,0.01,0.001,0.0001,0])
param_grid = dict(alpha=alphas)
model = Ridge()
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3)
grid.fit(X, Y)
print(grid.best_score_)
print(grid.best_estimator_.alpha)

0.2796175593129721
1.0

In [14]:
data.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [16]:
import pickle
from sklearn.model_selection import train_test_split

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
test_size= 0.33
X_train,X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=7)
model = LogisticRegression(solver='liblinear')
model.fit(X_train, Y_train)
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...

# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)
print(result)

0.7559055118110236